sonar.projectKey=OmniTrustILM_pyadcs-connector
sonar.organization=ilm

sonar.sources=pyadcs_connector
sonar.tests=pyadcs_connector
sonar.test.inclusions=**/tests.py,**/test_*.py
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=**/tests.py,**/test_*.py,**/migrations/**,pyadcs_connector/pyadcs_connector/**,**/manage.py
sonar.cpd.exclusions=**/tests.py,**/test_*.py,**/migrations/**
